### PR TITLE
bump to 1.13 and small fixes

### PR DESCRIPTION
**Pull request by ilya84**
EOM does not builds when 'gtk3' and 'dbus' use-flags enabled together. Add REQUIRED_USE for this situation. Also removed --mate-conf and --user-guide configure switches from mate-base/mate-desktop.
Build succesfully mate-base/mate with deps on gtk3 use-flag enabled.

### CODE REVIEW

**Comment by oz123** [comment]
@ilya84 , 

> removed --mate-conf and --user-guide

Are they not supported any more?

**Comment by ilya84** [comment]
yes, user-guide is in a separate package (QA reports wrong configure switch in mate-desktop for this)
and --mate-conf removed in 1.13 as 'ancient': https://github.com/mate-desktop/mate-desktop/blob/master/NEWS

**Comment by ilya84** [comment]
and i found error in my edition of eom-1.13.0, will prepeare PR in a minute

**Comment by ilya84** [comment]
i need help with git, where we could consult privately?

**Comment by oz123** [comment]
You could reach me on #gentoo on irc.freenode, (ozn or oznt), but I am not always online. 
If you want you can use git rebase to re-edit your commit. Or simply make new commits to your branch.
The PR will be updated automatically.

BTW, thank your for the effort.

**Comment by ilya84** [comment]
okay, that's all for here, i don't have another changes, last commit was really last :)

**Comment by ilya84** [comment]
ups.. it seems, i did something wrong

**Comment by oz123** [comment]
@ilya84 , can we merge this or not?

**Comment by ilya84** [comment]
yes, that's all with this

**Pull request merged**
