### PR TITLE
Add current MATE 1.14 minor versions

### PR DESCRIPTION
**Pull request by geki-yaba**
Well, if you can cherry-pick, skip 2b6af19 a5b1b03 d69bfaa 827e54e - I hope next time I get it done properly.

### CODE REVIEW

**Comment by geki-yaba** [comment]
I made some git helper scripts to commit package-wise and compare latest versions of packages.
Latest versions seemed to have no changes; no -rX revision packages checked.

See: https://github.com/geki-yaba/gekis-playground/tree/master/scripts

**Comment by geki-yaba** [comment]
If you want x11-themes/mate-themes-1.14.10-r20 for gtk-3.20.x, let me know. Green-Submarine theme has some glitches in lightdm and .11 shows some applts always being highlighted, though. Reported upstream, let's see.

Therefore its KEYWORDS is empty.

**Comment by oz123** [comment]
@geki-yaba  can you say which scripts you mean, and please and some documentation how you use the scripts?

**Comment by geki-yaba** [comment]
The scripts would be 'git_commit_pkgwise' and 'git_compare_latest'.

I can do documentation on my next spare time.
Sadly, I have spent all of it for now.

**Comment by oz123** [comment]
@geki-yaba well, that is a bummer, I have no clue what this scripts are, and guessing what their for won't help. I will try and merge your PR later this week. In the mean while, if you want to skip commits, you can just use `git rebase -i` to remove the unwanted commits so I don't have to cherry-pick.

**Comment by oz123** [comment]
I merged your changes excluding the commit you mentions. Thanks!

**Pull request closed without merging**
